---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Download SSM Installer from AWS
  get_url:
    url: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    dest: /tmp/ssm_installer.rpm
    mode: '0777'

- name: Install SSM Agent using ZYPPER
  zypper:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    state: present
  notify: Restart SSM Agent service