---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Get mounted disks
  shell: lsblk -io MOUNTPOINT
  register: mounted_folder_list

- name: Set fact for all disks mounted
  set_fact: all_disks_mounted=true
  when: item in mounted_folder_list.stdout_lines
  with_items:
    - "{{ sap_folder }}"
    - "{{ sapmnt_folder }}"
    - "{{ sap_swap }}"