---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Set Instance hostname HA for Hana
  include_tasks: set_instance_hostname_ha_hana.yml
  when: GLOBAL_HANA_SID is defined

- name: Set Instance hostname HA for ASCS/ERS
  include_tasks: set_instance_hostname_ha_ascs_ers.yml
  when: GLOBAL_ERS_SID is defined or GLOBAL_ASCS_SID is defined