---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Ensure /etc/security/limits.d/99-sap.conf exists
  stat:
    path: "{{ sap_limits_conf_file_path }}"
  register: stat_result

- name: Create the file, if it doesn't alredy exists
  file:
    path: "{{ sap_limits_conf_file_path }}"
    state: touch
  when: not stat_result.stat.exists

- name: Add configs to 99-sap.conf
  lineinfile:
    name: "{{ sap_limits_conf_file_path }}"
    line: "{{ item.user }}    {{ item.mode }}    {{ item.proc }}    {{ item.value }}"
    state: present
    insertafter: EOF
  loop: "{{ sap_limits_conf_file_content }}"

- name: Copy sap.conf to /etc/tmpfiles.d/sap.conf
  copy:
    src: "{{ role_path }}/files/sap.conf"
    dest: /etc/tmpfiles.d/sap.conf
    mode: 0755

- name: Config clocksource
  include_tasks: config_clocksource.yml

- name: Copy files
  include_tasks: copy_files.yml

- name: Config grub
  include_tasks: config_grub.yml

- name: Config grub2-mkconfig
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg