---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

sap_conf_file_path: /etc/sysctl.d/sap.conf
sap_limits_conf_file_path: /etc/security/limits.d/99-sap.conf
system_clocksource_file: /sys/devices/system/clocksource/clocksource0/current_clocksource
grub_file_default_path: /etc/default/grub

sysctl_configs:
  - param: kernel.pid_max
    value: 4194304
  - param: net.core.somaxconn
    value: 4096
  - param: net.ipv4.tcp_max_syn_backlog
    value: 8192
  - param: net.ipv4.tcp_slow_start_after_idle
    value: 0

sap_conf_file_content:
  - param: net.core.somaxconn
    value: 4096
  - param: net.ipv4.tcp_max_syn_backlog
    value: 8192
  - param: net.ipv4.tcp_slow_start_after_idle
    value: 0
  - param: kernel.pid_max
    value: 4194304

sysctl_enable_autofs_nfs:  
  - nfs-server
  - autofs

sap_limits_conf_file_content:
  - user: "@sapsys"
    mode: hard
    proc: nofile
    value: 65536
  - user: "@sapsys"
    mode: soft
    proc: nofile
    value: 65536
  - user: "@sapsys"
    mode: hard
    proc: nproc
    value: unlimited
  - user: "@sapsys"
    mode: soft
    proc: nproc
    value: unlimited