---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

# Common roles for preparing the image
- name: Check inputs, prepare logs, hostname, install basic dependencies and AWS Data Provider
  become: yes
  hosts: all
  roles:
    - role: check-inputs
      vars:
        input_variables_to_check: 
          - EC2_HOSTNAME
          - PRIVATE_DNS_ZONE
          - MASTER_PASSWORD
          - HANA_SID
          - HANA_INSTANCE_NUMBER
          - EFS_ID
          - S3_BUCKET_MEDIA_FILES
          - ENABLE_HA
          - AWS_CLI_PROFILE
    - role: common-os-tasks
    - role: prepare-logs-folders
    - role: install-pkg-mgr-dependencies
    - role: install-aws-sap-data-provider
    - role: set-hostname
      vars:
        extra_vars_to_add_to_hosts:
          - private_ip: "{{ GLOBAL_ASCS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_ASCS_HOSTNAME }}"
          - private_ip: "{{ GLOBAL_PAS_PRIVATE_IP }}"
            hostname: "{{ GLOBAL_PAS_HOSTNAME }}"

# Installation-specific roles
- name: Set parameters and mount disks
  become: yes
  hosts: all
  roles:
    - role: ansible-role-parameters
    - role: ansible-role-disks

# RedHat official roles for preparing for SAP Installation
- name: Prepare host with RedHat certified roles
  become: yes
  hosts: all
  roles:
    - role: sap-preconfigure
      vars:
        sap_preconfigure_selinux_state: disabled
        sap_preconfigure_fail_if_reboot_required: false
    - role: sap-hana-preconfigure
      vars:
        sap_hana_preconfigure_fail_if_reboot_required: false

# Hana installation roles
- name: Download and Install Hana
  become: yes
  hosts: all
  roles:
    - role: ansible-role-download-and-install

- name: Enable HA
  become: yes
  hosts: all
  roles:
    - role: ansible-role-enable-ha