---

# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

- name: Remove used credentials
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ db_params_file_full_path }}"
    - "{{ pas_params_file_full_path }}"
